Fix missing title in "telemetry" frontmatter
CI was failing because this page was missing a title:

    11:35:10 === RUN   TestFrontMatterTitle
    11:35:10 --- FAIL: TestFrontMatterTitle (0.12s)
    11:35:10 	frontmatter_test.go:27: can't find title in frontmatter - /docs/enterprise/telemetry.md

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>